package ai.koog.agents.core.tools

import ai.koog.agents.core.tools.annotations.InternalAgentToolsApi
import ai.koog.agents.core.tools.serialization.ToolJson
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonObject

/**
 * This interface serves as a safeguard for controlling direct tool calls from outside
 * of the AIAgent or Environment context.
 *
 * Tool calls must not be performed by a user directly as this might cause issues
 * and side-effects, such as:
 * - Missing EventHandler events
 * - Bugs with feature pipelines
 * - Inability to test/mock
 * - And other potential problems
 *
 * For this reason, all tools should be called using the environment context.
 * Consider using methods like `findTool(tool: Class)` or similar, to retrieve a
 * `SafeTool`, and then call `execute` on it. This ensures that the tool call is
 * delegated properly to the underlying `environment` object.
 *
 * @suppress
 */
@InternalAgentToolsApi
public interface DirectToolCallsEnabler


/**
 * Represents a generic, abstract tool with support for arguments, execution results, and metadata.
 * The Tool class is designed to provide a flexible and extensible framework for defining tools that
 * process input arguments and produce type-safe results.
 *
 * @param TArgs The type of arguments required by the tool's execution.
 * @param TResult The type of results produced by the tool's execution.
 */
@Suppress("UNCHECKED_CAST", "unused")
public abstract class Tool<TArgs : ToolArgs, TResult : ToolResult> {

    /**
     * Wrapper class for encapsulating the result of a tool execution. This class combines
     * the tool being invoked, the arguments used, and the resulting data, both internal and external.
     *
     * @property smartToolCall The tool being executed, represented as an instance of `Tool` with its associated argument and result types.
     * @property args The arguments provided to the tool during execution.
     * @property internalData The internal result generated by the tool, if available. This can contain intermediate or auxiliary data.
     * @property externalData The primary result of the tool execution, representing the external/output data produced.
     */
    public data class ToolResultWrapper(
        val smartToolCall: Tool<*, *>,
        val args: ToolArgs,
        val internalData: ToolResult?,
        val externalData: ToolResult,
    ) : ToolResult {
        override fun toStringDefault(): String = externalData.toStringDefault()
    }

    private val _toolCalls = MutableStateFlow(listOf<ToolResultWrapper>())

    /**
     * Provides a read-only flow of tool execution results.
     * This property maintains a history of all tool executions and their corresponding results.
     * The flow emits an updated list whenever a new tool call is completed.
     *
     * @return A [StateFlow] containing a list of [ToolResultWrapper] instances representing the history of tool executions.
     */
    public val toolCalls: StateFlow<List<ToolResultWrapper>> = _toolCalls.asStateFlow()

    private fun addToolCallResult(toolCall: ToolResultWrapper) {
        _toolCalls.update { it + toolCall }
    }

    /**
     * Returns the number of times a specific tool type has been called.
     *
     * @param T The specific tool type to count the executions for
     * @return The total number of times the specified tool type has been executed
     */
    public inline fun <reified T : Tool<TArgs, TResult>> count(): Int =
        toolCalls.value.count { it.smartToolCall is T }

    /**
     * Retrieves the execution results for a specific tool type.
     *
     * @param T The specific tool type to get results for
     * @return A list of execution results for the specified tool type, or null if no executions exist
     */
    public inline fun <reified T : Tool<TArgs, TResult>> results(): List<ToolResultWrapper>? =
        toolCalls.value.filter { it.smartToolCall is T }.takeIf { it.isNotEmpty() }

    /**
     * Gets the internal result data from the most recent execution of a specific tool type.
     *
     * @param T The specific tool type
     * @return The internal result data from the last execution, or null if no executions exist
     */
    public inline fun <reified T : Tool<TArgs, TResult>> lastInternalResult(): ToolResult? =
        toolCalls.value.lastOrNull { it.smartToolCall is T }?.internalData

    /**
     * Retrieves the external result data from the most recent execution of a specific tool type.
     *
     * @param T The specific tool type to get the external result for.
     * @return The external result data from the last execution of the specified tool type, or null if no executions exist.
     */
    public inline fun <reified T : Tool<TArgs, TResult>> lastExternalResult(): ToolResult? =
        toolCalls.value.lastOrNull { it.smartToolCall is T }?.externalData

    /**
     * Serializer responsible for encoding and decoding the arguments required for the tool execution.
     * This abstract property is used to define the specific [KSerializer] corresponding to the type of arguments
     * expected by the tool.
     *
     * The implementation must provide a concrete serializer for the `TArgs` type parameter, which ensures
     * proper serialization and deserialization of the tool arguments.
     */
    public abstract val argsSerializer: KSerializer<TArgs>

    /**
     * Provides a descriptor detailing the tool's metadata, including its name,
     * description, and parameter requirements. This property defines the structure
     * and characteristics of the tool, offering an overview of its functionality
     * and how it should be used.
     */
    public abstract val descriptor: ToolDescriptor

    /**
     * Represents the name property of the tool, derived from the tool's descriptor.
     * This property provides an immutable reference to the tool's unique name,
     * which is used for identification within tool registries.
     */
    public val name: String get() = descriptor.name

    /**
     * Executes the tool's logic with the provided arguments through a custom execution body.
     *
     * @param args The input arguments for execution
     * @param body A function that processes the arguments and returns a result wrapper
     * @return The execution result
     */
    public open suspend fun executeWithContext(args: TArgs, body: suspend (TArgs) -> ToolResultWrapper): ToolResult {
        val result = body(args)
        addToolCallResult(result)
        return result.externalData
    }

    /**
     * Executes the tool's logic with the provided arguments.
     *
     * Tool calls must not be performed directly by a user as this might cause issues
     * and side-effects, such as:
     * - Missing EventHandler events
     * - Bugs with feature pipelines
     * - Inability to test/mock
     * - And other potential problems
     *
     * For this reason, all tools should be called using the environment context.
     * Consider using methods like `findTool(tool: Class)` or similar, to retrieve a
     * `SafeTool`, and then call `execute` on it. This ensures that the tool call is
     * delegated properly to the underlying `environment` object.
     *
     * @param args The input arguments required to execute the tool.
     * @return The result of the tool's execution.
     */
    protected abstract suspend fun execute(args: TArgs): TResult

    /**
     * Executes the tool with the provided arguments, bypassing type safety checks.
     *
     * Tool calls must not be performed directly by a user as this might cause issues
     * and side-effects, such as:
     * - Missing EventHandler events
     * - Bugs with feature pipelines
     * - Inability to test/mock
     * - And other potential problems
     *
     * For this reason, all tools should be called using the environment context.
     * Consider using methods like `findTool(tool: Class)` or similar, to retrieve a
     * `SafeTool`, and then call `execute` on it. This ensures that the tool call is
     * delegated properly to the underlying `environment` object.
     *
     * This method allows the execution of the tool using arguments of any type, casting them to the expected type internally.
     * It requires a `DirectToolCallsEnabler` to validate that the unsafe execution is intentional and properly encapsulated.
     *
     * @param args The input arguments for the tool execution, provided as a generic `Any?` type. The method attempts to cast this to the expected argument type `TArgs`.
     * @param enabler An instance of `DirectToolCallsEnabler` that authorizes this unsafe execution path. Direct calls without proper enabling are not allowed.
     * @return The result of executing the tool, as an instance of type `TResult`.
     * @throws ClassCastException if the provided arguments cannot be cast to the expected type `TArgs`.
     *
     * @suppress
     */
    @InternalAgentToolsApi
    public suspend fun executeUnsafe(args: Any?, enabler: DirectToolCallsEnabler): TResult = execute(args as TArgs)

    /**
     * Executes the tool using the provided arguments and enabler.
     *
     * Tool calls must not be performed directly by a user as this might cause issues
     * and side-effects, such as:
     * - Missing EventHandler events
     * - Bugs with feature pipelines
     * - Inability to test/mock
     * - And other potential problems
     *
     * For this reason, all tools should be called using the environment context.
     * Consider using methods like `findTool(tool: Class)` or similar, to retrieve a
     * `SafeTool`, and then call `execute` on it. This ensures that the tool call is
     * delegated properly to the underlying `environment` object.
     *
     * @param args The arguments of type TArgs that are required for the execution of the tool.
     * @param enabler An instance of DirectToolCallsEnabler that ensures direct tool calls are controlled within the proper context.
     * @return The result of type TResult produced by executing the tool with the provided arguments.
     *
     * @suppress
     */
    @InternalAgentToolsApi
    public suspend fun execute(args: TArgs, enabler: DirectToolCallsEnabler): TResult = execute(args)

    /**
     * Decodes the provided raw JSON arguments into an instance of the specified arguments type.
     *
     * @param rawArgs the raw JSON object that contains the encoded arguments
     * @return the decoded arguments of type TArgs
     */
    public fun decodeArgs(rawArgs: JsonObject): TArgs = ToolJson.decodeFromJsonElement(argsSerializer, rawArgs)

    /**
     * Encodes the given arguments into a JSON representation.
     *
     * @param args The arguments to be encoded.
     * @return A JsonObject representing the encoded arguments.
     */
    public fun encodeArgs(args: TArgs): JsonObject = ToolJson.encodeToJsonElement(argsSerializer, args).jsonObject

    /**
     * Encodes the provided arguments into a JSON string representation using the configured serializer.
     *
     * @param args the arguments to be encoded into a JSON string
     * @return the JSON string representation of the provided arguments
     */
    public fun encodeArgsToString(args: TArgs): String = ToolJson.encodeToString(argsSerializer, args)

    /**
     * Encodes the given result of type TResult to its string representation for the LLM.s
     *
     * @param result The result object of type TResult to be encoded into a string.
     * @return The string representation of the given result.
     */
    public open fun encodeResultToString(result: TResult): String = result.toStringDefault()

    /**
     * Encodes the provided result object into a JSON string representation without type safety checks.
     *
     * This method casts the given result to the expected `TResult` type and uses the `resultSerializer`
     * to encode it into a string. Use with caution, as it bypasses type safety and may throw runtime exceptions
     * if the cast fails.
     *
     * @param result The result object of type `Tool.Result` to be encoded.
     * @return A JSON string representation of the provided result.
     */
    public fun encodeResultToStringUnsafe(result: ToolResult): String = encodeResultToString(result as TResult)

    /**
     * Base type, representing tool arguments.
     */
    @Deprecated("Use ToolArgs instead", ReplaceWith("ToolArgs", "ai.koog.agents.core.tools.ToolArgs"))
    public interface Args : ToolArgs

    /**
     * Args implementation that can be used for tools that expect no arguments.
     */
    @Serializable
    @Deprecated("Use ToolArgs.Empty instead", ReplaceWith("ToolArgs.Empty", "ai.koog.agents.core.tools.ToolArgs.Empty"))
    public data object EmptyArgs : Args
}
